--
-- PostgreSQL database dump
--

\restrict AnxvarpDqs42W6F1g9S1F43tBdBRjeIMBHyJjb8qVRnE94iN470YVIzHRLhGqi9

-- Dumped from database version 17.10 (Debian 17.10-0+deb13u1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-0+deb13u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: cdt_db; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE cdt_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'es_CO.UTF-8';


ALTER DATABASE cdt_db OWNER TO postgres;

\unrestrict AnxvarpDqs42W6F1g9S1F43tBdBRjeIMBHyJjb8qVRnE94iN470YVIzHRLhGqi9
\connect cdt_db
\restrict AnxvarpDqs42W6F1g9S1F43tBdBRjeIMBHyJjb8qVRnE94iN470YVIzHRLhGqi9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: inversion; Type: TABLE; Schema: public; Owner: jpa_user
--

CREATE TABLE public.inversion (
    id integer NOT NULL,
    nombre_inversion character varying(255) NOT NULL,
    monto_inversion double precision NOT NULL,
    plazo_en_dias integer NOT NULL,
    tasa double precision NOT NULL,
    ganancia_bruta double precision,
    ganancia_neta double precision,
    usuario_id integer NOT NULL
);


ALTER TABLE public.inversion OWNER TO jpa_user;

--
-- Name: inversion_id_seq; Type: SEQUENCE; Schema: public; Owner: jpa_user
--

ALTER TABLE public.inversion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inversion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: jpa_user
--

CREATE TABLE public.usuario (
    id integer NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.usuario OWNER TO jpa_user;

--
-- Name: listar_usuarios; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.listar_usuarios AS
 SELECT id,
    nombre
   FROM public.usuario;


ALTER VIEW public.listar_usuarios OWNER TO postgres;

--
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: jpa_user
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inversion inversion_pkey; Type: CONSTRAINT; Schema: public; Owner: jpa_user
--

ALTER TABLE ONLY public.inversion
    ADD CONSTRAINT inversion_pkey PRIMARY KEY (id);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: jpa_user
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- Name: inversion inversion_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jpa_user
--

ALTER TABLE ONLY public.inversion
    ADD CONSTRAINT inversion_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuario(id) ON DELETE CASCADE;


--
-- Name: DATABASE cdt_db; Type: ACL; Schema: -; Owner: postgres
--

GRANT ALL ON DATABASE cdt_db TO jpa_user;


--
-- PostgreSQL database dump complete
--

\unrestrict AnxvarpDqs42W6F1g9S1F43tBdBRjeIMBHyJjb8qVRnE94iN470YVIzHRLhGqi9

